/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import lectura.ImageManager;

/**
 *
 * @author Roberto Cruz Leija
 */
public class GrisJInternalFrame extends javax.swing.JInternalFrame {

    private JInternalFrame jInternalImagen;
    private Image imagenOriginal;
    private Image imagenResultante;
    /**
     * Creates new form GrisJInternalFrame
     */
    public GrisJInternalFrame(JInternalFrame jInternalImagen) {
        initComponents();
        this.jInternalImagen = jInternalImagen;
        actualizarImagen(); 
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonGrises = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));

        jButtonGrises.setText("Escala de Grises ");
        jButtonGrises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGrisesMouseClicked(evt);
            }
        });

        jButtonActualizar.setText("Actualizar Imagen");
        jButtonActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGrises, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButtonGrises)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonActualizar)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGrisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGrisesMouseClicked
         this.imagenResultante = filtrosespaciales.FiltroEspacial.generaEscalaGrises(imagenOriginal);
         this.jLabel1.setIcon(new ImageIcon(imagenResultante));
    }//GEN-LAST:event_jButtonGrisesMouseClicked

    private void jButtonActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonActualizarMouseClicked
        ImagenJInternalFrame frame = (ImagenJInternalFrame)this.jInternalImagen;
        frame.modificarImagen(imagenResultante);
    }//GEN-LAST:event_jButtonActualizarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonGrises;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void actualizarImagen() {
       ImagenJInternalFrame frame = (ImagenJInternalFrame)this.jInternalImagen;
       imagenOriginal =ImageManager.toImage(ImageManager.toBufferedImage(frame.getImagenOriginal()));
       this.jLabel1.setIcon(new ImageIcon(imagenOriginal));
    }
}
